version: "3.9"

networks:
  myfood-network:
    driver: bridge

services:
  myfood-mysql:
    image: mysql:8.0
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    ports:
      - "3306:3306"
    networks:
      - myfood-network

  myfood-api:
    image: myfood-api:latest
    command: ["/wait-for-it.sh","myfood-mysql:3306","-t","30","--","java", "-jar", "api.jar"]
    environment:
      DB_HOST: myfood-mysql
    ports:
      - "8080:8080"
    networks:
      - myfood-network
    depends_on:
      - myfood-mysql